export const ADD_TO_CART = "ADD_TO_CART";

export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";

export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";

export const REMOVE_ALL_CART_ITEM = "REMOVE_ALL_CART_ITEM";

export const ADD_TO_CART_FAIL="ADD_TO_CART_FAIL"
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS"

export const REMOVE_TO_CART_SUCCESS="REMOVE_TO_CART_SUCCESS"
export const REMOVE_TO_CART_FAIL="REMOVE_TO_CART_FAIL"

export const UPDATE_TO_CART_SUCCESS = "UPDATE_TO_CART_SUCCESS"
export const UPDATE_TO_CART = "UPDATE_TO_CART"
export const UPDATE_TO_CART_FAIL="UPDATE_TO_CART_FAIL"
export const GET_CART_SUCCESS="GET_CART_SUCCESS"
export const GET_CART_FAIL="GET_CART_FAIL"
export const GET_CART_ITEM ="GET_CART_ITEM"

export const REMOVE_ALL_CART_ITEM_SUCCESS = "REMOVE_ALL_CART_ITEM_SUCCESS"
export const REMOVE_ALL_CART_ITEM_FAIL="REMOVE_ALL_CART_ITEM_FAIL"
export const DELETE_ALL_CART_RESET="DELETE_ALL_CART_RESET"
export const ADD_CART_RESET="ADD_CART_RESET"
export const CLEAR_ERRORS ="CLEAR_ERRORS "
export const UPDATE_CART_RESET="UPDATE_CART_RESET"
export const DELETE_CART_RESET="DELETE_CART_RESET"